export const ROUTES = {
  home: "/",
  products: "/products",
  productDetails: "/products/:id",
  login: "/auth/login",
  register: "/auth/register",
  wishlist: "wishlist",
  basket: "basket",
  checkout: "checkout",
  layout: "layout",
  orders: "/dashboard/orders",
  ourStaff: "/dashboard/ourStaff",
  dashboardProducts: "/dashboard/products",
  productItem: "/dashboard/products/:id",
  brands: "/dashboard/brands",
  orderInvoice: "/dashboard/orders/orderInvoice",
} as const;
